#!/usr/bin/env python3
"""License gate for assets/: every shipped file must appear in a MANIFEST.json
with an allowed license, and every manifest entry must exist. Writes
assets/CREDITS.md from the manifests. Exit 1 on any problem."""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
ALLOWED = {"CC0-1.0", "CC-BY-3.0", "CC-BY-4.0", "generated"}
ATTRIBUTION = {"CC-BY-3.0", "CC-BY-4.0"}
SKIP_SUFFIXES = {".import", ".md"}
SKIP_NAMES = {"MANIFEST.json", ".gdignore", ".DS_Store"}


def main() -> int:
    problems = []
    entries = []
    license_files = set()
    for manifest in sorted(ASSETS.glob("*/MANIFEST.json")):
        for e in json.loads(manifest.read_text()):
            entries.append(e)
            for lf in license_paths(e):
                license_files.add((ROOT / lf).resolve())
    listed = {}
    for e in entries:
        path = (ROOT / e["file"]).resolve()
        listed[path] = e
        if not path.exists():
            problems.append(f"listed but missing: {e['file']}")
        if e.get("license") not in ALLOWED:
            problems.append(f"license not allowed ({e.get('license')}): {e['file']}")
        for lf in license_paths(e):
            if not (ROOT / lf).exists():
                problems.append(f"license file missing: {lf}")
    for f in sorted(ASSETS.rglob("*")):
        if not f.is_file() or f.name in SKIP_NAMES or f.suffix in SKIP_SUFFIXES:
            continue
        if f.resolve() in license_files or "licenses" in f.parts:
            continue
        if f.name.lower().startswith("license") and f.suffix == ".txt":
            continue
        if f.resolve() not in listed and not extracted_texture(f, listed):
            problems.append(f"unlisted file: {f.relative_to(ROOT)}")

    write_credits(entries)
    for p in problems:
        print(p)
    print(f"assets: {len(listed)} listed, {len(problems)} problems")
    return 1 if problems else 0


def extracted_texture(f: pathlib.Path, listed: dict) -> bool:
    """Godot's importer writes a model's embedded textures next to it as
    <model>_<texture>.png; they carry the model's license."""
    if f.suffix.lower() not in {".png", ".jpg", ".jpeg", ".webp"}:
        return False
    for model in listed:
        if model.parent == f.parent.resolve() and model.suffix.lower() in {".glb", ".fbx"}:
            if f.name.startswith(model.stem + "_"):
                return True
    return False


def license_paths(entry: dict) -> list:
    """Layered sounds list several license files joined by ' | '."""
    return [p.strip() for p in entry.get("license_file", "").split("|") if p.strip()]


def write_credits(entries: list) -> None:
    packs = {}
    for e in entries:
        key = (e.get("pack", "?"), e.get("author", "?"), e.get("license", "?"))
        packs.setdefault(key, set()).add(e.get("source_url", ""))
    lines = [
        "# Credits",
        "",
        "Generated by `tools/check_assets.py` from the MANIFEST.json files. Per-file",
        "sources are in each manifest.",
        "",
        "## Attribution required (CC-BY)",
        "",
    ]
    by = sorted(k for k in packs if k[2] in ATTRIBUTION)
    for pack, author, lic in by:
        urls = ", ".join(sorted(u for u in packs[(pack, author, lic)] if u))
        lines.append(f"- **{pack}** by {author} — {lic} — {urls}")
    lines += ["", "## Public domain (CC0) and generated", ""]
    for pack, author, lic in sorted(k for k in packs if k[2] not in ATTRIBUTION):
        lines.append(f"- {pack} by {author} — {lic}")
    (ASSETS / "CREDITS.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    sys.exit(main())
