#!/usr/bin/env python3
"""Writes src/audio/audio_trims.gd: one gain per file in
assets/audio/MANIFEST.json that brings every sound to a common loudness, so
the mix table in audio_mix.gd sets balance instead of fighting source levels.

One-shots are measured by their loudest 400 ms (EBU R128 momentary, padded so
very short clips still register); music and looping beds by integrated
loudness. Needs ffmpeg. Rerun after adding or replacing audio:
    python3 tools/measure_audio_trims.py && gdformat src/audio/audio_trims.gd
"""
import json
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
AUDIO = ROOT / "assets" / "audio"
OUT = ROOT / "src" / "audio" / "audio_trims.gd"
ONE_SHOT_TARGET = -12.0
LOOP_TARGET = -16.0
LIMIT = 12.0


def loudness(path: pathlib.Path) -> tuple:
    log = subprocess.run(
        ["ffmpeg", "-hide_banner", "-nostats", "-i", str(path), "-af", "apad=pad_dur=0.5,ebur128",
         "-f", "null", "-"],
        capture_output=True, text=True, check=True,
    ).stderr
    integrated = float(re.findall(r"I:\s+(-?[\d.]+) LUFS", log)[-1])
    momentary = max(float(m) for m in re.findall(r" M:\s*(-?[\d.]+)", log))
    return integrated, momentary


def is_loop(path: pathlib.Path) -> bool:
    if path.parent.name == "music":
        return True
    imported = path.with_name(path.name + ".import")
    return imported.exists() and "\nloop=true" in imported.read_text()


def main() -> None:
    lines = []
    for entry in json.loads((AUDIO / "MANIFEST.json").read_text()):
        path = ROOT / entry["file"]
        integrated, momentary = loudness(path)
        if is_loop(path):
            trim = LOOP_TARGET - integrated
        else:
            trim = ONE_SHOT_TARGET - momentary
        trim = max(-LIMIT, min(LIMIT, trim))
        rel = path.relative_to(AUDIO).as_posix()
        lines.append(f'\t"{rel}": {trim:.1f},')
    OUT.write_text(
        "class_name AudioTrims\n"
        "extends RefCounted\n"
        "## Per-file gain in dB that levels every sound before the mix table applies:\n"
        f"## one-shots to {ONE_SHOT_TARGET:.0f} LUFS loudest-moment, loops to {LOOP_TARGET:.0f} LUFS\n"
        "## integrated. Generated by src/audio/measure_trims.py; do not edit by hand.\n"
        "\n"
        "const DB := {\n" + "\n".join(lines) + "\n}\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(lines)} files)")


if __name__ == "__main__":
    main()
